#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <sys/socket.h>     // socket, bind, listen, accept, sockaddr, socklen_t
#include <netinet/ip.h>     // sockaddr_in, htons
#include <arpa/inet.h>      // INADDR_ANY
#include <sys/epoll.h>      // epoll_wait
#include <netdb.h>
#include <sys/types.h>

#define FALSE 0
#define TRUE 1

#define DECIMAL_NUM 10

#define LISTENING_BACKLOG 50

#define SUCCESS 0
#define INCORRECT_CMD_ARGS 1

#define EXPECTED_ARGS 2

#define IP_ARG 1
#define PORT_ARG 2

#define HOST_MAX_LEN 1024

int usage(char * message)
{
    printf("Expected ./client <ip> <port>\n%s\n", message);
    return INCORRECT_CMD_ARGS;
}

int string_to_int(int * num, char * str)
{
    char *end;
    *num = strtol(str, &end, DECIMAL_NUM);

    //TODO: maybe make sure num is not too long?

    if(end == str || *end != '\0')
    {
        return FALSE;
    }

    return TRUE;
}

//Generated by chat
int print_host_network_info()
{
	char hostname[HOST_MAX_LEN];
	memset(hostname, 0, HOST_MAX_LEN);

    //make sure last char is '\0'
	gethostname(hostname, HOST_MAX_LEN - 1);

    struct addrinfo hints, *res, *p;
    int status;

    memset(&hints, 0, sizeof(hints));
    hints.ai_family = AF_INET;        // IPv4
    hints.ai_socktype = SOCK_STREAM;  // TCP

    if ((status = getaddrinfo(hostname, NULL, &hints, &res)) != 0) {
        fprintf(stderr, "getaddrinfo: %s\n", gai_strerror(status));
        return 1;
    }

    for (p = res; p != NULL; p = p->ai_next) {
        char ipstr[INET_ADDRSTRLEN];
        struct sockaddr_in *ipv4 = (struct sockaddr_in *)p->ai_addr;
        void *addr = &(ipv4->sin_addr);

        inet_ntop(p->ai_family, addr, ipstr, sizeof(ipstr));
        printf("Hostname: %s\n", hostname);
        printf("IP Address: %s\n", ipstr);
    }

    freeaddrinfo(res);
    return 0;

}

int main(int argc, char ** argv)
{
	
	int quit = 0;
	int num_args = argc - 1;
	if(num_args != EXPECTED_ARGS)
	{
		return usage("You can only have 2 argument");
	}

	int sfd = socket(AF_INET, SOCK_STREAM, 0);

	//check if valid socket file descriptor
	if(sfd == -1)
	{
		printf("Error Creating Socket: %s\n", strerror(errno));
		return 1;
	}

	char * server_ip = argv[IP_ARG];
	
    int port;
	if(!string_to_int(&port, argv[PORT_ARG]))
	{
		return usage("you did not give a number for the port");
	}
	
    struct sockaddr_in addr;
    //clear struct
    memset(&addr, 0, sizeof(struct sockaddr_in));
    //AF_INET domain address
    addr.sin_family = AF_INET;
    addr.sin_port = htons(port);
    if(inet_aton(server_ip, &addr.sin_addr) == -1)
	{
		printf("Error Setting IP: %s\n", strerror(errno));
		return 1;
	}

	if(connect(sfd, (struct sockaddr *) &addr, sizeof(struct sockaddr_in)) == -1)
	{
		printf("Error Connecting: %s\n", strerror(errno));
		return 1;
	}
	
    print_host_network_info();

	if(close(sfd) == -1)
	{
		printf("Failed to close: %s\n", strerror(errno));
		return 1;
	}

	return 0;
}

