#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <sys/socket.h>     // socket, bind, listen, accept, sockaddr, socklen_t
#include <netinet/ip.h>     // sockaddr_in, htons
#include <arpa/inet.h>      // INADDR_ANY
#include <sys/epoll.h>      // epoll_wait
#include <netdb.h>
#include <sys/types.h>

#define FALSE 0
#define TRUE 1

#define DECIMAL_NUM 10

#define LISTENING_BACKLOG 50

#define SUCCESS 0
#define INCORRECT_CMD_ARGS 1

#define EXPECTED_ARGS 2

#define IP_ARG 1
#define PORT_ARG 2

#define HOST_MAX_LEN 1024

#define BUFFER_RW_SIZE 1024

#define DELIMITER '\n'

//Balanced AVL Tree created partly by me and partly by chatgpt

struct btree {
    struct btree *left;
    struct btree *right;
    int line_num;
    char *line;
    int height;
};

// Utility: get node height (NULL nodes have height 0)
static int height(struct btree *n) {
    return n ? n->height : 0;
}

// Utility: max of two ints
static int max(int a, int b) {
    return (a > b) ? a : b;
}

// Create a new node
static struct btree *new_node(int line_num, const char *line) {
    struct btree *node = malloc(sizeof(*node));
    if (!node) return NULL;
    node->line_num = line_num;
    node->line = strdup(line);
    node->left = node->right = NULL;
    node->height = 1;  // new node is initially a leaf
    return node;
}

// Right-rotate subtree rooted at y
static struct btree *right_rotate(struct btree *y) {
    struct btree *x = y->left;
    struct btree *T2 = x->right;

    // Perform rotation
    x->right = y;
    y->left = T2;

    // Update heights
    y->height = max(height(y->left), height(y->right)) + 1;
    x->height = max(height(x->left), height(x->right)) + 1;

    // Return new root
    return x;
}

// Left-rotate subtree rooted at x
static struct btree *left_rotate(struct btree *x) {
    struct btree *y = x->right;
    struct btree *T2 = y->left;

    // Perform rotation
    y->left = x;
    x->right = T2;

    // Update heights
    x->height = max(height(x->left), height(x->right)) + 1;
    y->height = max(height(y->left), height(y->right)) + 1;

    // Return new root
    return y;
}

// Get balance factor of node (left height minus right height)
static int get_balance(struct btree *n) {
    return n ? height(n->left) - height(n->right) : 0;
}

// Insert a key/value into the AVL tree, rebalancing as needed
struct btree *add(struct btree *node, int line_num, const char *line) {
    // 1. Perform standard BST insertion
    if (!node)
        return new_node(line_num, line);

    if (line_num < node->line_num)
        node->left = add(node->left, line_num, line);
    else if (line_num > node->line_num)
        node->right = add(node->right, line_num, line);
    else
        return node; // Duplicate keys not allowed; ignore or handle as needed

    // 2. Update height of this ancestor node
    node->height = 1 + max(height(node->left), height(node->right));

    // 3. Get the balance factor
    int balance = get_balance(node);

    // 4. If unbalanced, there are 4 cases
    // Left Left Case
    if (balance > 1 && line_num < node->left->line_num)
        return right_rotate(node);

    // Right Right Case
    if (balance < -1 && line_num > node->right->line_num)
        return left_rotate(node);

    // Left Right Case
    if (balance > 1 && line_num > node->left->line_num) {
        node->left = left_rotate(node->left);
        return right_rotate(node);
    }

    // Right Left Case
    if (balance < -1 && line_num < node->right->line_num) {
        node->right = right_rotate(node->right);
        return left_rotate(node);
    }

    // Return the (unchanged) node pointer
    return node;
}

// Free all nodes in the tree
void free_all(struct btree *root) {
    if (!root) return;
    free_all(root->left);
    free_all(root->right);
    free(root->line);
    free(root);
}

int usage(char * message)
{
    printf("Expected ./client <ip> <port>\n%s\n", message);
    return INCORRECT_CMD_ARGS;
}

int string_to_int(int * num, char * str)
{
    char *end;
    *num = strtol(str, &end, DECIMAL_NUM);

    //TODO: maybe make sure num is not too long?

    if(end == str || *end != '\0')
    {
        return FALSE;
    }

    return TRUE;
}

//Generated by chat
int print_host_network_info()
{
	char hostname[HOST_MAX_LEN];
	memset(hostname, 0, HOST_MAX_LEN);

    //make sure last char is '\0'
	gethostname(hostname, HOST_MAX_LEN - 1);

    struct addrinfo hints, *res, *p;
    int status;

    memset(&hints, 0, sizeof(hints));
    hints.ai_family = AF_INET;        // IPv4
    hints.ai_socktype = SOCK_STREAM;  // TCP

    if ((status = getaddrinfo(hostname, NULL, &hints, &res)) != 0) {
        fprintf(stderr, "getaddrinfo: %s\n", gai_strerror(status));
        return 1;
    }

    for (p = res; p != NULL; p = p->ai_next) {
        char ipstr[INET_ADDRSTRLEN];
        struct sockaddr_in *ipv4 = (struct sockaddr_in *)p->ai_addr;
        void *addr = &(ipv4->sin_addr);

        inet_ntop(p->ai_family, addr, ipstr, sizeof(ipstr));
        printf("Hostname: %s\n", hostname);
        printf("IP Address: %s\n", ipstr);
    }

    freeaddrinfo(res);
    return 0;

}

int main(int argc, char ** argv)
{
	
	int quit = 0;
	int num_args = argc - 1;
	if(num_args != EXPECTED_ARGS)
	{
		return usage("You can only have 2 argument");
	}

	int sfd = socket(AF_INET, SOCK_STREAM, 0);

	//check if valid socket file descriptor
	if(sfd == -1)
	{
		printf("Error Creating Socket: %s\n", strerror(errno));
		return 1;
	}

	char * server_ip = argv[IP_ARG];
	
    int port;
	if(!string_to_int(&port, argv[PORT_ARG]))
	{
		return usage("you did not give a number for the port");
	}
	
    struct sockaddr_in addr;
    //clear struct
    memset(&addr, 0, sizeof(struct sockaddr_in));
    //AF_INET domain address
    addr.sin_family = AF_INET;
    addr.sin_port = htons(port);
    if(inet_aton(server_ip, &addr.sin_addr) == -1)
	{
		printf("Error Setting IP: %s\n", strerror(errno));
		return 1;
	}

	if(connect(sfd, (struct sockaddr *) &addr, sizeof(struct sockaddr_in)) == -1)
	{
		printf("Error Connecting: %s\n", strerror(errno));
		return 1;
	}
	
    print_host_network_info();

    char buf [BUFFER_RW_SIZE];

    while(read(sfd, buf, BUFFER_RW_SIZE) != EOF)
    {
        
    }

	if(close(sfd) == -1)
	{
		printf("Failed to close: %s\n", strerror(errno));
		return 1;
	}

	return 0;
}

