#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <sys/socket.h>     // socket, bind, listen, accept, sockaddr, socklen_t
#include <netinet/ip.h>     // sockaddr_in, htons
#include <arpa/inet.h>      // INADDR_ANY
#include <sys/epoll.h>      // epoll_wait
#include <netdb.h>
#include <sys/types.h>


#define FALSE 0
#define TRUE 1

//main function return values
#define SUCCESS 0
#define INCORRECT_CMD_ARGS 1
#define CMD_LINE_FILE_DNE 2
#define NO_ORIGINAL_FILE 3
#define BAD_FRAGMENT 4
#define SOCKET_ISSUE 5

#define EXPECTED_ARGS 2

//argv index of arguments
#define FILE_ARG 1
#define PORT_ARG 2

#define DECIMAL_NUM 10

//constants for socket functions
#define LISTENING_BACKLOG 50
#define HOST_MAX_LEN 1024

int usage(char * message)
{

    printf("Expected ./server <filename> <port>\n%s\n", message);
    return INCORRECT_CMD_ARGS;
}

int string_to_int(int * num, char * str)
{
    char *end;
    *num = strtol(str, &end, DECIMAL_NUM);

    //TODO: maybe make sure num is not too long?

    if(end == str || *end != '\0')
    {
        return FALSE;
    }

    return TRUE;
}

//Generated by chat
int print_host_network_info()
{
	char hostname[HOST_MAX_LEN];
	memset(hostname, 0, HOST_MAX_LEN);

    //make sure last char is '\0'
	gethostname(hostname, HOST_MAX_LEN - 1);

    struct addrinfo hints, *res, *p;
    int status;

    memset(&hints, 0, sizeof(hints));
    hints.ai_family = AF_INET;        // IPv4
    hints.ai_socktype = SOCK_STREAM;  // TCP

    if ((status = getaddrinfo(hostname, NULL, &hints, &res)) != 0) {
        fprintf(stderr, "getaddrinfo: %s\n", gai_strerror(status));
        return 1;
    }

    for (p = res; p != NULL; p = p->ai_next) {
        char ipstr[INET_ADDRSTRLEN];
        struct sockaddr_in *ipv4 = (struct sockaddr_in *)p->ai_addr;
        void *addr = &(ipv4->sin_addr);

        inet_ntop(p->ai_family, addr, ipstr, sizeof(ipstr));
        printf("Hostname: %s\n", hostname);
        printf("IP Address: %s\n", ipstr);
    }

    freeaddrinfo(res);
    return 0;

}

//Generated by chat
void print_socket_details(int sockfd) {
    // We'll use a sockaddr_storage to support both IPv4 and IPv6.
    struct sockaddr_storage addr;
    socklen_t addr_len = sizeof(addr);

    // Retrieve the local socket address.
    if (getpeername(sockfd, (struct sockaddr *)&addr, &addr_len) != 0) {
        perror("getsockname");
        return;
    }

    char ipstr[INET6_ADDRSTRLEN];
    char service[NI_MAXSERV];
    char hostname[NI_MAXHOST];

    // Use getnameinfo to convert the socket address into a human-readable format.
    // NI_NUMERICHOST flag ensures we get the numerical IP address,
    // NI_NUMERICSERV flag ensures we get the port number as a string.
    int flags = NI_NUMERICHOST | NI_NUMERICSERV;
    int res = getnameinfo((struct sockaddr *)&addr, addr_len,
                          hostname, sizeof(hostname),
                          service, sizeof(service),
                          flags);
    if (res != 0) {
        fprintf(stderr, "getnameinfo: %s\n", gai_strerror(res));
        return;
    }

    // Alternatively, we can also extract the IP string manually:
    if (addr.ss_family == AF_INET) {  // IPv4
        struct sockaddr_in *s = (struct sockaddr_in *)&addr;
        inet_ntop(AF_INET, &(s->sin_addr), ipstr, sizeof(ipstr));
    } else if (addr.ss_family == AF_INET6) {  // IPv6
        struct sockaddr_in6 *s = (struct sockaddr_in6 *)&addr;
        inet_ntop(AF_INET6, &(s->sin6_addr), ipstr, sizeof(ipstr));
    } else {
        strncpy(ipstr, "Unknown AF", sizeof(ipstr));
    }

    // Convert the port string from getnameinfo to an integer if needed.
    int port = atoi(service);

    // Print the details.
    printf("IP Address: %s\n", ipstr);
    printf("Port: %d\n", port);
}

//connects the connected client and print out client info
int handle_connection(int sfd)
{
    struct sockaddr_in c_addr;
    socklen_t clen = sizeof(struct sockaddr_in);
    cfd = accept(sfd, (struct sockaddr *) &c_addr, &clen );

    if(cfd == -1)
    {
        printf("Error Accepting Connection: %s\n", strerror(errno));
        return SOCKET_ISSUE;
    }
    printf("Made new connection\n");

    print_socket_details(cfd);

    ev.events = EPOLLIN | EPOLLRDHUP;
    ev.data.fd = cfd;
    if (epoll_ctl(epfd, EPOLL_CTL_ADD, cfd, &ev) == -1) {
        perror("epoll_ctl: client add");
        return 1;
    }
    return SUCCESS;
}

int main(int argc, char * argv[])
{
    int num_args = argc - 1;

    if(num_args != EXPECTED_ARGS)
    {
        return usage("you used incorrect num args");
    }

    int port;
    if(!string_to_int(&port, argv[PORT_ARG]))
    {
        return usage("the port you specified was not an int");
    }
    printf("PORT: %d\n", port);

    FILE * file_cmd_input = fopen(argv[FILE_ARG], "r");
    if(file_cmd_input == NULL)
    {
        printf("the file you specified does not exist");
        return CMD_LINE_FILE_DNE;
    }

    //go through lines of file given file
    char *line = NULL;
    size_t size = 0;
    ssize_t nread;

    if((nread = getline(&line, &size, file_cmd_input)) == -1)
    {
        printf("No original file was given\n");
        return NO_ORIGINAL_FILE;
    }

    //turn end of line char '\n' into '\0'
    line[nread - 1] = '\0';

    FILE * file_original = fopen(line, "r");

    FILE ** fragment_files = NULL;
    int index = 0;

    while ((nread = getline(&line, &size, file_cmd_input)) != -1) {
        line[nread - 1] = '\0';
        fragment_files = (FILE**) realloc(fragment_files, sizeof(FILE *) * (index + 1));
        fragment_files[index] = fopen(line, "r");
        
        if(fragment_files[index] == NULL)
        {
            printf("Fragment[%d] did not open\nFile name given: %s\n", index, line);
            return BAD_FRAGMENT;
        }

        index++;
    }

    int num_fragment_files = index;

    //we are done looking through the cmd line file
    free(line);
    fclose(file_cmd_input);

    //SOCKET TIME YO!

    int sfd = socket(AF_INET, SOCK_STREAM, 0);

    //check if valid socket file descriptor
    if(sfd == -1)
    {
        printf("Error Creating Socket: %s\n", strerror(errno));
        return SOCKET_ISSUE;
    } 

    struct sockaddr_in addr;
    //clear struct
    memset(&addr, 0, sizeof(struct sockaddr_in));
    //AF_INET domain address
    addr.sin_family = AF_INET;
    addr.sin_port = htons(port);
    addr.sin_addr.s_addr = INADDR_ANY;

    if(bind(sfd, (struct sockaddr *) &addr, sizeof(struct sockaddr_in)) == -1)
    {
        printf("Error Binding Socket: %s\n", strerror(errno));
        return SOCKET_ISSUE;
    }


    if(listen(sfd, LISTENING_BACKLOG) == -1)
    {
        printf("Error Setting up Socket to Listen: %s\n", strerror(errno));
        return SOCKET_ISSUE;
    }

    print_host_network_info();

    //Going to use epoll to wait for clients
    int epfd = epoll_create1(0);

	struct epoll_event * evlist = (struct epoll_event *) malloc(sizeof(struct epoll_event) * num_fragment_files);

	//add event listener for stdin
	struct epoll_event ev;
	ev.events = EPOLLIN;
	ev.data.fd = sfd;

	if (epoll_ctl(epfd, EPOLL_CTL_ADD, sfd, &ev) == -1)
	{
		printf("Error Setting up epoll STDIN: %s\n", strerror(errno));
		return 1;
	}

    int file_index = 0;
    int cont = 1;
    int cfd;
    int ret_val;
    while(cont)
	{
        int num_events = epoll_wait(epfd, evlist, num_fragment_files, -1);

        for(int i = 0; i < num_events; i++)
        {
            int fd = evlist[i].data.fd;
			uint32_t events = evlist[i].events;

            //New Connection!
            if ((fd == sfd) && (events & EPOLLIN)) {
				struct sockaddr_in c_addr;
                socklen_t clen = sizeof(struct sockaddr_in);
                cfd = accept(sfd, (struct sockaddr *) &c_addr, &clen );

                if(cfd == -1)
                {
                    printf("Error Accepting Connection: %s\n", strerror(errno));
                    return SOCKET_ISSUE;
                }
                printf("Made new connection\n");

                print_socket_details(cfd);

                ev.events = EPOLLIN | EPOLLRDHUP;
                ev.data.fd = cfd;
                if (epoll_ctl(epfd, EPOLL_CTL_ADD, cfd, &ev) == -1) {
                    perror("epoll_ctl: client add");
                    return 1;
                }

                //send data from current file to client
                FILE * file_to_send = fragment_files[file_index];
                int line_index = 0;
                while ((nread = getline(&line, &size, file_to_send)) != -1) {
                    
                    fprintf(file_to_send, line);
                }

                //increment file index to prepare sending next file
                file_index++;

                return SUCCESS;
                
			}

            //Receiving Info from client!
            if((fd != sfd) && (events & EPOLLIN))
            {
                char buf[1024];
                read(fd, buf, 1023);
            }

            //Client Disconnecting!
            if((fd != sfd) && (events & EPOLLRDHUP))
            {
                printf("Client disconnected!\n");
				ev.events = EPOLLIN | EPOLLRDHUP;
				ev.data.fd = cfd;
				epoll_ctl(epfd, EPOLL_CTL_DEL, cfd, NULL);
				close(cfd);
            }
        }

		
    }

    //close and free all opened files
    fclose(file_original);
    for(int i = 0; i < num_fragment_files; i++)
    {
        fclose(fragment_files[i]);
    }
    free(fragment_files);

    //free epoll structure
    free(evlist);

    return SUCCESS;

}