#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <sys/socket.h>     // socket, bind, listen, accept, sockaddr, socklen_t
#include <netinet/ip.h>     // sockaddr_in, htons
#include <arpa/inet.h>      // INADDR_ANY
#include <sys/epoll.h>      // epoll_wait
#include <netdb.h>
#include <sys/types.h>


#define FALSE 0
#define TRUE 1

//main function return values
#define SUCCESS 0
#define INCORRECT_CMD_ARGS 1
#define CMD_LINE_FILE_DNE 2
#define NO_ORIGINAL_FILE 3
#define BAD_FRAGMENT 4
#define SOCKET_ISSUE 5
#define EPOLL_ISSUE 6

#define EXPECTED_ARGS 2

//argv index of arguments
#define FILE_ARG 1
#define PORT_ARG 2

#define DECIMAL_NUM 10

//constants for socket functions
#define LISTENING_BACKLOG 50
#define HOST_MAX_LEN 1024

#define BUFFER_RW_SIZE 1024


//Balanced AVL Tree created partly by me and partly by chatgpt

struct btree {
    struct btree *left;
    struct btree *right;
    int line_num;
    char *line;
    int height;
};

// Utility: get node height (NULL nodes have height 0)
static int height(struct btree *n) {
    return n ? n->height : 0;
}

// Utility: max of two ints
static int max(int a, int b) {
    return (a > b) ? a : b;
}

// Create a new node
static struct btree *new_node(int line_num, const char *line) {
    struct btree *node = malloc(sizeof(*node));
    if (!node) return NULL;
    node->line_num = line_num;
    node->line = strdup(line);
    node->left = node->right = NULL;
    node->height = 1;  // new node is initially a leaf
    return node;
}

// Right-rotate subtree rooted at y
static struct btree *right_rotate(struct btree *y) {
    struct btree *x = y->left;
    struct btree *T2 = x->right;

    // Perform rotation
    x->right = y;
    y->left = T2;

    // Update heights
    y->height = max(height(y->left), height(y->right)) + 1;
    x->height = max(height(x->left), height(x->right)) + 1;

    // Return new root
    return x;
}

// Left-rotate subtree rooted at x
static struct btree *left_rotate(struct btree *x) {
    struct btree *y = x->right;
    struct btree *T2 = y->left;

    // Perform rotation
    y->left = x;
    x->right = T2;

    // Update heights
    x->height = max(height(x->left), height(x->right)) + 1;
    y->height = max(height(y->left), height(y->right)) + 1;

    // Return new root
    return y;
}

// Get balance factor of node (left height minus right height)
static int get_balance(struct btree *n) {
    return n ? height(n->left) - height(n->right) : 0;
}

// Insert a key/value into the AVL tree, rebalancing as needed
struct btree *add(struct btree *node, int line_num, const char *line) {
    // 1. Perform standard BST insertion
    if (!node)
        return new_node(line_num, line);

    if (line_num < node->line_num)
        node->left = add(node->left, line_num, line);
    else if (line_num > node->line_num)
        node->right = add(node->right, line_num, line);
    else
        return node; // Duplicate keys not allowed; ignore or handle as needed

    // 2. Update height of this ancestor node
    node->height = 1 + max(height(node->left), height(node->right));

    // 3. Get the balance factor
    int balance = get_balance(node);

    // 4. If unbalanced, there are 4 cases
    // Left Left Case
    if (balance > 1 && line_num < node->left->line_num)
        return right_rotate(node);

    // Right Right Case
    if (balance < -1 && line_num > node->right->line_num)
        return left_rotate(node);

    // Left Right Case
    if (balance > 1 && line_num > node->left->line_num) {
        node->left = left_rotate(node->left);
        return right_rotate(node);
    }

    // Right Left Case
    if (balance < -1 && line_num < node->right->line_num) {
        node->right = right_rotate(node->right);
        return left_rotate(node);
    }

    // Return the (unchanged) node pointer
    return node;
}

// Free all nodes in the tree
void free_all(struct btree *root) {
    if (!root) return;
    free_all(root->left);
    free_all(root->right);
    free(root->line);
    free(root);
}


int usage(char * message)
{

    printf("Expected ./server <filename> <port>\n%s\n", message);
    return INCORRECT_CMD_ARGS;
}

int string_to_int(int * num, char * str)
{
    char *end;
    *num = strtol(str, &end, DECIMAL_NUM);

    //TODO: maybe make sure num is not too long?

    if(end == str || *end != '\0')
    {
        return FALSE;
    }

    return TRUE;
}

//Generated by chat
int print_host_network_info()
{
	char hostname[HOST_MAX_LEN];
	memset(hostname, 0, HOST_MAX_LEN);

    //make sure last char is '\0'
	gethostname(hostname, HOST_MAX_LEN - 1);

    struct addrinfo hints, *res, *p;
    int status;

    memset(&hints, 0, sizeof(hints));
    hints.ai_family = AF_INET;        // IPv4
    hints.ai_socktype = SOCK_STREAM;  // TCP

    if ((status = getaddrinfo(hostname, NULL, &hints, &res)) != 0) {
        fprintf(stderr, "getaddrinfo: %s\n", gai_strerror(status));
        return 1;
    }

    for (p = res; p != NULL; p = p->ai_next) {
        char ipstr[INET_ADDRSTRLEN];
        struct sockaddr_in *ipv4 = (struct sockaddr_in *)p->ai_addr;
        void *addr = &(ipv4->sin_addr);

        inet_ntop(p->ai_family, addr, ipstr, sizeof(ipstr));
        printf("Hostname: %s\n", hostname);
        printf("IP Address: %s\n", ipstr);
    }

    freeaddrinfo(res);
    return 0;

}

//Generated by chat
void print_socket_details(int sockfd) {
    // We'll use a sockaddr_storage to support both IPv4 and IPv6.
    struct sockaddr_storage addr;
    socklen_t addr_len = sizeof(addr);

    // Retrieve the local socket address.
    if (getpeername(sockfd, (struct sockaddr *)&addr, &addr_len) != 0) {
        perror("getsockname");
        return;
    }

    char ipstr[INET6_ADDRSTRLEN];
    char service[NI_MAXSERV];
    char hostname[NI_MAXHOST];

    // Use getnameinfo to convert the socket address into a human-readable format.
    // NI_NUMERICHOST flag ensures we get the numerical IP address,
    // NI_NUMERICSERV flag ensures we get the port number as a string.
    int flags = NI_NUMERICHOST | NI_NUMERICSERV;
    int res = getnameinfo((struct sockaddr *)&addr, addr_len,
                          hostname, sizeof(hostname),
                          service, sizeof(service),
                          flags);
    if (res != 0) {
        fprintf(stderr, "getnameinfo: %s\n", gai_strerror(res));
        return;
    }

    // Alternatively, we can also extract the IP string manually:
    if (addr.ss_family == AF_INET) {  // IPv4
        struct sockaddr_in *s = (struct sockaddr_in *)&addr;
        inet_ntop(AF_INET, &(s->sin_addr), ipstr, sizeof(ipstr));
    } else if (addr.ss_family == AF_INET6) {  // IPv6
        struct sockaddr_in6 *s = (struct sockaddr_in6 *)&addr;
        inet_ntop(AF_INET6, &(s->sin6_addr), ipstr, sizeof(ipstr));
    } else {
        strncpy(ipstr, "Unknown AF", sizeof(ipstr));
    }

    // Convert the port string from getnameinfo to an integer if needed.
    int port = atoi(service);

    // Print the details.
    printf("IP Address: %s\n", ipstr);
    printf("Port: %d\n", port);
}

//connects the connected client and print out client info
int handle_connection(int sfd)
{
    struct sockaddr_in c_addr;
    socklen_t clen = sizeof(struct sockaddr_in);
    cfd = accept(sfd, (struct sockaddr *) &c_addr, &clen );

    if(cfd == -1)
    {
        printf("Error Accepting Connection: %s\n", strerror(errno));
        return SOCKET_ISSUE;
    }
    printf("Made new connection\n");

    print_socket_details(cfd);

    ev.events = EPOLLIN | EPOLLRDHUP;
    ev.data.fd = cfd;
    if (epoll_ctl(epfd, EPOLL_CTL_ADD, cfd, &ev) == -1) {
        perror("epoll_ctl: client add");
        return 1;
    }
    return SUCCESS;
}

int main(int argc, char * argv[])
{
    int num_args = argc - 1;

    if(num_args != EXPECTED_ARGS)
    {
        return usage("you used incorrect num args");
    }

    int port;
    if(!string_to_int(&port, argv[PORT_ARG]))
    {
        return usage("the port you specified was not an int");
    }
    printf("PORT: %d\n", port);

    FILE * file_cmd_input = fopen(argv[FILE_ARG], "r");
    if(file_cmd_input == NULL)
    {
        printf("the file you specified does not exist");
        return CMD_LINE_FILE_DNE;
    }

    //go through lines of file given file
    char *line = NULL;
    size_t size = 0;
    ssize_t nread;

    if((nread = getline(&line, &size, file_cmd_input)) == -1)
    {
        printf("No original file was given\n");
        return NO_ORIGINAL_FILE;
    }

    //turn end of line char '\n' into '\0'
    line[nread - 1] = '\0';

    FILE * file_original = fopen(line, "r");

    int * fragment_files = NULL;
    int index = 0;

    while ((nread = getline(&line, &size, file_cmd_input)) != -1) {
        line[nread - 1] = '\0';
        fragment_files = (int *) realloc(fragment_files, sizeof(int) * (index + 1));
        fragment_files[index] = open(line, O_RDONLY);
        
        if(fragment_files[index] == NULL)
        {
            printf("Fragment[%d] did not open\nFile name given: %s\n", index, line);
            return BAD_FRAGMENT;
        }

        index++;
    }

    int num_fragment_files = index;

    //we are done looking through the cmd line file
    free(line);
    fclose(file_cmd_input);

    //SOCKET TIME YO!

    int sfd = socket(AF_INET, SOCK_STREAM, 0);

    //check if valid socket file descriptor
    if(sfd == -1)
    {
        printf("Error Creating Socket: %s\n", strerror(errno));
        return SOCKET_ISSUE;
    } 

    struct sockaddr_in addr;
    //clear struct
    memset(&addr, 0, sizeof(struct sockaddr_in));
    //AF_INET domain address
    addr.sin_family = AF_INET;
    addr.sin_port = htons(port);
    addr.sin_addr.s_addr = INADDR_ANY;

    if(bind(sfd, (struct sockaddr *) &addr, sizeof(struct sockaddr_in)) == -1)
    {
        printf("Error Binding Socket: %s\n", strerror(errno));
        return SOCKET_ISSUE;
    }


    if(listen(sfd, LISTENING_BACKLOG) == -1)
    {
        printf("Error Setting up Socket to Listen: %s\n", strerror(errno));
        return SOCKET_ISSUE;
    }

    print_host_network_info();

    //Going to use epoll to wait for clients
    int epfd = epoll_create1(0);

	struct epoll_event * evlist = (struct epoll_event *) malloc(sizeof(struct epoll_event) * num_fragment_files);

	//add event listener for stdin
	struct epoll_event ev;
	ev.events = EPOLLIN;
	ev.data.fd = sfd;

	if (epoll_ctl(epfd, EPOLL_CTL_ADD, sfd, &ev) == -1)
	{
		printf("Error Setting up epoll STDIN: %s\n", strerror(errno));
		return 1;
	}

    int file_index = 0;
    int cont = 1;
    int cfd;
    int ret_val;
    while(cont)
	{
        int num_events = epoll_wait(epfd, evlist, num_fragment_files, -1);

        for(int i = 0; i < num_events; i++)
        {
            int fd = evlist[i].data.fd;
			uint32_t events = evlist[i].events;

            //New Connection!
            if ((fd == sfd) && (events & EPOLLIN)) {
				struct sockaddr_in c_addr;
                socklen_t clen = sizeof(struct sockaddr_in);
                cfd = accept(sfd, (struct sockaddr *) &c_addr, &clen );

                if(cfd == -1)
                {
                    printf("Error Accepting Connection: %s\n", strerror(errno));
                    return SOCKET_ISSUE;
                }
                printf("Made new connection\n");

                print_socket_details(cfd);

                ev.events = EPOLLIN | EPOLLRDHUP;
                ev.data.fd = cfd;
                if (epoll_ctl(epfd, EPOLL_CTL_ADD, cfd, &ev) == -1) {
                    printf("Error Adding to EPOLL: %s\n", strerror(errno));
                    return EPOLL_ISSUE;
                }

                //TODO: Change this to send a fixed amount of client (so the client can make sure it receieved the right amount of bits)
                //TODO: Switch from FILE pointers to file descriptors
                //send data from current file to client
                int file_to_send_fd = fragment_files[file_index];
                char buffer[BUFFER_RW_SIZE];
                ssize_t bytesRead;
                while (read(file_to_send_fd, buffer, sizeof(buffer) - 1) != -1) {

                    printf("Sending file fragment %d to a client\n", file_index);
                    write(file_to_send_fd, buffer, sizeof(buffer) - 1);

                }

                //increment file index to prepare sending next file
                file_index++;

                return SUCCESS;
                
			}

            //Receiving Info from client!
            if((fd != sfd) && (events & EPOLLIN))
            {
                char buf[1024];
                read(fd, buf, 1023);
            }

            //Client Disconnecting!
            if((fd != sfd) && (events & EPOLLRDHUP))
            {
                printf("Client disconnected!\n");
				ev.events = EPOLLIN | EPOLLRDHUP;
				ev.data.fd = cfd;
				epoll_ctl(epfd, EPOLL_CTL_DEL, cfd, NULL);
				close(cfd);
            }
        }

		
    }

    //close and free all opened files
    fclose(file_original);
    for(int i = 0; i < num_fragment_files; i++)
    {
        fclose(fragment_files[i]);
    }
    free(fragment_files);

    //free epoll structure
    free(evlist);

    return SUCCESS;

}